# Generated by Django 4.2.21 on 2025-08-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField()),
            ],
        ),
    ]
