# Generated by Django 4.2.21 on 2025-08-01 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dollo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('cv', models.CharField(max_length=255)),
                ('id_offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='dollo.offre')),
            ],
        ),
    ]
